version: '3.4'

services:
  myapp:
    image: myapp
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
  backend:
    image: webapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5241:5241
