version: '3.4'

services:
  myapp:
    image: myapp
    depends_on:
      foodloyaleapi:
        condition:  service_health 
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
